### ISSUE TITLE
Calculation of Vss and Vd after oral administration

### ISSUE THREAD

**Issue by lindauer1980** [Open-Systems-Pharmacology/OSP-based-publications-and-content#194]
Hi,

I noticed that the calculated values of Vss and Vd in "Show PK-Analysis" following oral administration of the drug does not result in the same values as when the same simulation is run manually using IV administration. 
As I understand from the manual, total bioavailability after oral administration is calculated from an IV-simulation running behind de scenes. However, it seems that the other secondary parameters Vss and Vd are then not derived from this IV-simulation, but rather calculated from the oral Vss/F (or Vd/F) multiplied with F.
If this is the case I would suggest changing this, such that after clicking the 'Bioavailability' button Vss and Vd are derived in the same way as when running an IV-simulation manually.

Regards, Andreas.

**Comment by msevestre** [comment]
Hi @lindauer1980

Could you please create an issue with the same content in the PKSim repo ? This is where we discuss feature wishes and bugs. Thanks
