### ISSUE TITLE
Open Systems Pharmacology Community-An Open Access, Open Source, Open Science Approach to Modeling and Simulation in Pharmaceutical Sciences.

### ISSUE THREAD

**Issue by Stergiou** [Open-Systems-Pharmacology/OSP-based-publications-and-content#220]
CPT Pharmacometrics Syst Pharmacol. 2019 Dec;8(12):878-882. doi: 10.1002/psp4.12473. Epub 2019 Nov 12.

https://www.ncbi.nlm.nih.gov/pubmed/31671256

Lippert J1, Burghaus R1, Edginton A2, Frechen S1, Karlsson M3, Kovar A4, Lehr T5, Milligan P6, Nock V7, Ramusovic S4, Riggs M8, Schaller S9, Schlender J1, Schmidt S10, Sevestre M11, Sjögren E3,6, Solodenko J1, Staab A7, Teutonico D12.

PMID: 31671256 PMCID: PMC6930856 DOI: 10.1002/psp4.12473

**Comment by Yuri05** [comment]
duplicate
