### ISSUE TITLE
Physiologically-Based Pharmacokinetic Modeling Characterizes the CYP3A-Mediated Drug-Drug Interaction Between Fluconazole and Sildenafil in Infants 

### ISSUE THREAD

**Issue by JanSchlender** [Open-Systems-Pharmacology/OSP-based-publications-and-content#277]
https://pubmed.ncbi.nlm.nih.gov/32691891/
Clin Pharmacol Ther. 2020 Jul 21
Sara N Salerno, Andrea Edginton, Jacqueline G Gerhart, Matthew M Laughon, Namasivayam Ambalavanan, Gregory M Sokol, Chi D Hornik, Dan Stewart, Mary Mills, Karen Martz, Daniel Gonzalez

Abstract 
Physiologically-based pharmacokinetic (PBPK) modeling can potentially predict pediatric drug-drug interactions (DDIs) when clinical DDI data are limited. In infants for whom treatment of pulmonary hypertension and prevention or treatment of invasive candidiasis are indicated, sildenafil with fluconazole may be given concurrently. To account for developmental changes in cytochrome P450 (CYP) 3A, we determined and incorporated fluconazole inhibition constants (KI ) for CYP3A4, CYP3A5, and CYP3A7 into a PBPK model developed for sildenafil and its active metabolite, N-desmethylsildenafil. Pharmacokinetic (PK) data in preterm infants receiving sildenafil with and without fluconazole were used for model development and evaluation. The simulated PK parameters were comparable to observed values. Following fluconazole co-administration, differences in the fold change for simulated steady-state area under the plasma concentration vs. time curve from 0 to 24 hours (AUCss,0-24 ) were observed between virtual adults and infants (2.11-fold vs. 2.82-fold change). When given in combination with treatment doses of fluconazole (12 mg/kg i.v. daily), reducing the sildenafil dose by ~ 60% resulted in a geometric mean ratio of 1.01 for simulated AUCss,0-24 relative to virtual infants receiving sildenafil alone. This study highlights the feasibility of PBPK modeling to predict DDIs in infants and the need to include CYP3A7 parameters. 
© 2020 The Authors. Clinical Pharmacology & Therapeutics published by Wiley Periodicals LLC on behalf of American Society for Clinical Pharmacology and Therapeutics.

**Comment by AndreDlm** [comment]
Duplicate with https://github.com/Open-Systems-Pharmacology/OSP-based-publications-and-content/issues/261
