### ISSUE TITLE
Physiologically Based Pharmacokinetic Modeling in Neonates: Current Status and Future Perspectives

### ISSUE THREAD

**Issue by JanSchlender** [Open-Systems-Pharmacology/OSP-based-publications-and-content#551]
https://pubmed.ncbi.nlm.nih.gov/38140105/
Pharmaceutics. 2023 Dec 12;15(12):2765. 
Wei Zhang, Qian Zhang, Zhihai Cao, Liang Zheng, Wei Hu

Abstract
Rational drug use in special populations is a clinical problem that doctors and pharma-cists must consider seriously. Neonates are the most physiologically immature and vulnerable to drug dosing. There is a pronounced difference in the anatomical and physiological profiles be-tween neonates and older people, affecting the absorption, distribution, metabolism, and excretion of drugs in vivo, ultimately leading to changes in drug concentration. Thus, dose adjustments in neonates are necessary to achieve adequate therapeutic concentrations and avoid drug toxicity. Over the past few decades, modeling and simulation techniques, especially physiologically based pharmacokinetic (PBPK) modeling, have been increasingly used in pediatric drug development and clinical therapy. This rigorously designed and verified model can effectively compensate for the deficiencies of clinical trials in neonates, provide a valuable reference for clinical research design, and even replace some clinical trials to predict drug plasma concentrations in newborns. This review introduces previous findings regarding age-dependent physiological changes and pathological factors affecting neonatal pharmacokinetics, along with their research means. The application of PBPK modeling in neonatal pharmacokinetic studies of various medications is also reviewed. Based on this, we propose future perspectives on neonatal PBPK modeling and hope for its broader application.

Keywords: PBPK; modeling and simulation; preterm infants; term infants.

**Comment by AndreDlm** [comment]
Duplicate of https://github.com/Open-Systems-Pharmacology/OSP-based-publications-and-content/issues/539
